### ISSUE TITLE
Is this repository still supported?

### ISSUE THREAD

**Issue by rkhwaja** [EdmundsAPI/sdk-python#9]
I would like a new pypi release of this library with the PRs accepted. Are you still supporting this library?
If not, I will probably make an "edmunds-python3" pypi package, or similar.

**Comment by neilengineer** [comment]
no, I'm just using it.

**Comment by rkhwaja** [comment]
I recently got an email from Edmunds saying that my type of usage of the API won't be allowed anymore so I won't be making a new package.
